### ISSUE TITLE
Long runtime + minor comments (See openjournals/joss-reviews#4773)

### ISSUE THREAD

**Issue by marastadler** [fatmasevinck/enetLTS#14]
Hi @fatmasevinck,

I'm in the process of reviewing `See openjournals/joss-reviews#4773`. Here are some comments on the code examples:

- The runtime of your examples is very long (for instance the multinomial example(`fit.multinom`) takes for me **18.78 mins**). You might consider improving the code to make it more time efficient. If this is not possible, you should mention in your tutorial that the runtime is quite long.

- Also, you should set a seed in your examples so that your results can be replicated.

- If you remove the ">" characters before the code lines it is more convenient for users to copy and try out your code.

**Comment by fatmasevinck** [comment]
Hi @marastadler,

Thanks for your comments, I am working on them.

**Comment by fatmasevinck** [comment]
Hi @marastadler 

Thank you for your comments. I have done your all suggestions.

**Comment by marastadler** [comment]
Hi @fatmasevinck,

Thanks for addressing the comments. 
After removing ">" characters from the sample code, the output of your code shouldn't be part of the code chunks. You can easily solve this by adding `eval = TRUE` to the chunk. 

Please also consider addressing the comments that I've made in the review thread regarding (typos, citation, plots, community guidelines and the chapter "related software")

**Comment by fabian-s** [comment]
@fatmasevinck please adress outstanding issues very soon, this has been under review for a very long time now.

as a courtesy to reviewers and me, please provide explicit links to the commits meant to fix specific issues and/or write informative commit messages so we know where to look for what.

**Comment by fatmasevinck** [comment]
Dear @marastadler

Many thanks for your suggestions and comments. 
I am working on them but there is something I could not understand which is that "After removing ">" characters from the sample code, the output of your code shouldn't be part of the code chunks. You can easily solve this by adding eval = TRUE to the chunk."
Here this R lines are only for having R format. When I added eval=TRUE to the chunk, style is broken. 
Maybe I missed something. If so, please could you give me more info what do you mean / is it ok in this way. 
Thanks again,

Sevinç

**Comment by fatmasevinck** [comment]
Dear @marastadler 

I think I have done everything you have suggested, except for the last comment. 
If I have missed something, your answer is very welcomed. 

Thanks, 
Sevinç

**Comment by marastadler** [comment]
> Dear @marastadler
> 
> Many thanks for your suggestions and comments. I am working on them but there is something I could not understand which is that "After removing ">" characters from the sample code, the output of your code shouldn't be part of the code chunks. You can easily solve this by adding eval = TRUE to the chunk." Here this R lines are only for having R format. When I added eval=TRUE to the chunk, style is broken. Maybe I missed something. If so, please could you give me more info what do you mean / is it ok in this way. Thanks again,
> 
> Sevinç

I see, so you shouldn't edit the .md-file via the console here on GitHub. You have to open this file as a .Rmd-file in R and render it to a GitHub document.

This is done as follows:

title: "..."
output: github_document


Once you push your repository it will appear in the correct format.

**Comment by marastadler** [comment]
> Dear @marastadler
> 
> I think I have done everything you have suggested, except for the last comment. If I have missed something, your answer is very welcomed.
> 
> Thanks, Sevinç

Dear @fatmasevinck,

Now I can see that you've fixed citations & typos in the .md file. But when downloading the article proof there are no updates. @fabian-s is it supposed to be like that?

From what I can see my other comments on community guidelines, coefficient plots and the chapter "related software" have not been addressed yet.

**Comment by fabian-s** [comment]
> Now I can see that you've fixed citations & typos in the .md file. But when downloading the article proof there are no updates. @fabian-s is it supposed to be like that?

are you referring to the `README.md` file of the repo or the JOSS paper that gets generated from `paper/paper.md` in this repo?  
The PDF for the latter needs to be re-generated from the updated `paper.md` file first, you can do that in the original review thread by running `@editorialbot generate pdf` -- i did just now, this should point to the latest version of the paper: https://github.com/openjournals/joss-reviews/issues/4773#issuecomment-1298246807

**Comment by fatmasevinck** [comment]
> > Dear @marastadler
> > I think I have done everything you have suggested, except for the last comment. If I have missed something, your answer is very welcomed.
> > Thanks, Sevinç
> 
> Dear @fatmasevinck,
> 
> Now I can see that you've fixed citations & typos in the .md file. But when downloading the article proof there are no updates. @fabian-s is it supposed to be like that?
> 
> From what I can see my other comments on community guidelines, coefficient plots and the chapter "related software" have not been addressed yet.

Dear @marastadler 

It seems you are talking about README.md file. I have written "related software" section in paper.md 
Is that ok in this way?

**Comment by fatmasevinck** [comment]
@fabian-s  we are on the same point at the same time, what a coincidence! 
Hope that this is ok for @marastadler  

Many thanks, 
Sevinç

**Comment by marastadler** [comment]
@fabian-s thanks for generating the pdf. I've been referring to `paper/paper.md` :-)

**Comment by marastadler** [comment]
@fatmasevinck all I'm saying is that my comment regarding the chapter "related software" has not been addressed so far.

Here's again the comment that I made:
In the chapter "related software" you name a few packages. It would be useful to elaborate a bit more on how these packages differ from enetLTS (e.g. would the package pense in the linear model case give the same results as enetLTS, or are they different and, if so, why?)

**Comment by fabian-s** [comment]
> It would be useful to elaborate a bit more on how these packages differ from enetLTS (e.g. would the package pense in the linear model case give the same results as enetLTS, or are they different and, if so, why?)

seconded

**Comment by fatmasevinck** [comment]
Dear @marastadler 

I added some sentences to the "related software" section. 

Thanks for your comments.

**Comment by fatmasevinck** [comment]
Dear @fabian-s 

Is there something that I should work on it? 
I finished everything and sent my answers before. 

Many thanks for your kind effort.
Sevinç

**Comment by fabian-s** [comment]
> From what I can see my other comments on community guidelines, coefficient plots and the chapter "related software" have not been addressed yet.

**Comment by fabian-s** [comment]
@marastadler have all your concerns been adressed in these recent commits?

@fatmasevinck once again, you would make this much easier for everybody if your replies/responses would specify which specific commits you intended to fix which specific issues.

**Comment by marastadler** [comment]
@fabian-s my comments were not or only superficially addressed yet. 
Here's again a summary of what's missing:
- Related software: The recently added comparison is quite superficial and also contains spelling and grammar mistakes.
- community guidelines are still missing
- I also find it still not user friendly to have both code and output (which is not commented out) in the chunks
- my comment concerning the presentation of the coefficients (third last figure in Readme.md) was not answered

**Comment by fabian-s** [comment]
@fatmasevinck  
please open a separate issue  for each of these unresolved points and reference them in the commit messages of the commits you make to address them

**Comment by fatmasevinck** [comment]
I have done this.
