### ISSUE TITLE
community guidelines

### ISSUE THREAD

**Issue by fatmasevinck** [fatmasevinck/enetLTS#18]
Dear @marastadler

Since enetLTS is a published R package, it has the help file. 
And enetLTS repo includes a README.md file. 
These files could be regarded as  community guidelines. 

Best, 
Sevinç

**Comment by fatmasevinck** [comment]
Dear @marastadler

You mentioned before 
https://github.com/fabian-sp/GGLasso

I can not see here what is community guidelines. 
Could you give me more info about it if possible? 
Tnx

**Comment by marastadler** [comment]
Dear @fatmasevinck,

it's in the CONTIBUTING.md 

See also the issue opened by @fabian-s: https://github.com/fatmasevinck/enetLTS/issues/16

**Comment by fatmasevinck** [comment]
@marastadler 
Many thanks for your developer comments, and hope that now the contributing part is ok. 

Best,
Sevinc
