### ISSUE TITLE
Your third comment

### ISSUE THREAD

**Issue by fatmasevinck** [fatmasevinck/enetLTS#20]
Dear @marastadler

"I also find it still not user friendly to have both code and output (which is not commented out) in the chunks"

I can not see what is the problem in having both code and output? 
I think it is good to see the code and and belonging output.

**Comment by marastadler** [comment]
@fatmasevinck Absolutely! Showing the output is a good thing for sure. 
Just not in the chunk, which is meant for users to copy and try out the code themselves. The minimum solution for this is to at least comment out the output. The nicer way is to show the output in separate chunks though.

**Comment by fatmasevinck** [comment]
@marastadler  I see your point now, thanks a lot. I am on it.

**Comment by fabian-s** [comment]
![image](https://user-images.githubusercontent.com/998541/208444961-501044be-f3de-43a2-a744-6aa4e4e8057f.png)

please use comments for the *output* of your code chunks.

I've requested this a couple of times now, please:  
use this issue tracker as intended to reply to specific issues, giving the specific commit hashes of the commits you made in order to fix the issues under discussion so I don't have to go through the entire paper or your commit logs every time to figure out if you changed something and where. 
you are making this much harder for everybody involved that it needs to be.

**Comment by fatmasevinck** [comment]
Dear @fabian-s 

I have added the comments as you recommend and I am giving the track here:

line 86: (for gaussian example)
23 out of 100 independent variables are selected by the enetLTS model based on optimal combination of $\alpha=$0.8 and $\lambda=$0.1043. Here $\lambda_w =$0.1824974 corresponds to updated tuning parameter for reweighted model. 

line 142:  (for binomal example)
48 out of 100 independent variables are selected by the enetLTS model based on optimal combination of $\alpha=0.325$ and $\lambda=0.0011$. Here $\lambda_w =0.01456879$ corresponds to updated tuning parameter for reweighted model. 

line 194: (for multinomial example)
704 out of 1096 independent variables are selected by the enetLTS model based on optimal combination of $\alpha=0.2$ and $\lambda=0.01$. Here $\lambda_w =0.003971358$ corresponds to updated tuning parameter for reweighted model. The effect of tuning parameter $\alpha$ on the model is very clear from less sparsity.

**Comment by fatmasevinck** [comment]
@fabian-s 

Many thanks for your supportive comments.

**Comment by fabian-s** [comment]
> I have added the comments as you recommend and I am giving the track here:

please take a look at any other published JOSS paper and how they format the code -- you were supposed to add proper code formatting to distinguish between code inputs and the resulting output and to enable people to simply copy-paste your code chunks into their console. 

you have:

```r
 # install and load package
install.packages("enetLTS")
# alternatively install package from Github
# library(devtools)
# install_github("fatmasevinck/enetLTS",force=TRUE)
library(enetLTS)
# fit the model for family="gaussian"
set.seed(1)
fit.gaussian <- enetLTS(X, y, crit.plot=TRUE)
[1] "optimal model: lambda = 0.1043 alpha = 0.8"

fit.gaussian

enetLTS estimator 

Call:  enetLTS(xx = X, yy = y, crit.plot=TRUE) 

 number of the nonzero coefficients:
[1] 23

 alpha: 0.8
 lambda: 0.1043
 lambdaw: 0.1824974
```
 
 you need:
 
```r
 # install and load package
install.packages("enetLTS")
# alternatively install package from Github
# library(devtools)
# install_github("fatmasevinck/enetLTS",force=TRUE)
library(enetLTS)
# fit the model for family="gaussian"
set.seed(1)
fit.gaussian <- enetLTS(X, y, crit.plot=TRUE)
## [1] "optimal model: lambda = 0.1043 alpha = 0.8"

fit.gaussian

## enetLTS estimator 

## Call:  enetLTS(xx = X, yy = y, crit.plot=TRUE) 

## number of the nonzero coefficients:
## [1] 23

##  alpha: 0.8
## lambda: 0.1043
## lambdaw: 0.1824974
 ``` 

please fix this throughout your paper and report back once that's done.

**Comment by fabian-s** [comment]
(you can also remove the text comments you added since they don't add any information)

**Comment by fatmasevinck** [comment]
@fabian-s 
Code parts are reorganized as you suggest, many thanks.

**Comment by fabian-s** [comment]
Pls fix  this:
![image](https://user-images.githubusercontent.com/998541/211800412-9bce0e55-1095-44da-b5e5-b70076feca9a.png)

**Comment by fatmasevinck** [comment]
It is done, tnx.
